package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BienesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBienesAllPropertiesEquals(Bienes expected, Bienes actual) {
        assertBienesAutoGeneratedPropertiesEquals(expected, actual);
        assertBienesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBienesAllUpdatablePropertiesEquals(Bienes expected, Bienes actual) {
        assertBienesUpdatableFieldsEquals(expected, actual);
        assertBienesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBienesAutoGeneratedPropertiesEquals(Bienes expected, Bienes actual) {
        assertThat(expected)
            .as("Verify Bienes auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBienesUpdatableFieldsEquals(Bienes expected, Bienes actual) {
        assertThat(expected)
            .as("Verify Bienes relevant properties")
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBienesUpdatableRelationshipsEquals(Bienes expected, Bienes actual) {}
}
