package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CentroEducativoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroEducativoAllPropertiesEquals(CentroEducativo expected, CentroEducativo actual) {
        assertCentroEducativoAutoGeneratedPropertiesEquals(expected, actual);
        assertCentroEducativoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroEducativoAllUpdatablePropertiesEquals(CentroEducativo expected, CentroEducativo actual) {
        assertCentroEducativoUpdatableFieldsEquals(expected, actual);
        assertCentroEducativoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroEducativoAutoGeneratedPropertiesEquals(CentroEducativo expected, CentroEducativo actual) {
        assertThat(expected)
            .as("Verify CentroEducativo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroEducativoUpdatableFieldsEquals(CentroEducativo expected, CentroEducativo actual) {
        assertThat(expected)
            .as("Verify CentroEducativo relevant properties")
            .satisfies(e -> assertThat(e.getCentroEducativo()).as("check centroEducativo").isEqualTo(actual.getCentroEducativo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroEducativoUpdatableRelationshipsEquals(CentroEducativo expected, CentroEducativo actual) {
        assertThat(expected)
            .as("Verify CentroEducativo relationships")
            .satisfies(e -> assertThat(e.getComuna()).as("check comuna").isEqualTo(actual.getComuna()));
    }
}
