package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ComunaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComunaAllPropertiesEquals(Comuna expected, Comuna actual) {
        assertComunaAutoGeneratedPropertiesEquals(expected, actual);
        assertComunaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComunaAllUpdatablePropertiesEquals(Comuna expected, Comuna actual) {
        assertComunaUpdatableFieldsEquals(expected, actual);
        assertComunaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComunaAutoGeneratedPropertiesEquals(Comuna expected, Comuna actual) {
        assertThat(expected)
            .as("Verify Comuna auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComunaUpdatableFieldsEquals(Comuna expected, Comuna actual) {
        assertThat(expected)
            .as("Verify Comuna relevant properties")
            .satisfies(e -> assertThat(e.getComuna()).as("check comuna").isEqualTo(actual.getComuna()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComunaUpdatableRelationshipsEquals(Comuna expected, Comuna actual) {}
}
