package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CuerpoTecnicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuerpoTecnicoAllPropertiesEquals(CuerpoTecnico expected, CuerpoTecnico actual) {
        assertCuerpoTecnicoAutoGeneratedPropertiesEquals(expected, actual);
        assertCuerpoTecnicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuerpoTecnicoAllUpdatablePropertiesEquals(CuerpoTecnico expected, CuerpoTecnico actual) {
        assertCuerpoTecnicoUpdatableFieldsEquals(expected, actual);
        assertCuerpoTecnicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuerpoTecnicoAutoGeneratedPropertiesEquals(CuerpoTecnico expected, CuerpoTecnico actual) {
        assertThat(expected)
            .as("Verify CuerpoTecnico auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuerpoTecnicoUpdatableFieldsEquals(CuerpoTecnico expected, CuerpoTecnico actual) {
        assertThat(expected)
            .as("Verify CuerpoTecnico relevant properties")
            .satisfies(e -> assertThat(e.getNombres()).as("check nombres").isEqualTo(actual.getNombres()))
            .satisfies(e -> assertThat(e.getApellidos()).as("check apellidos").isEqualTo(actual.getApellidos()))
            .satisfies(e -> assertThat(e.getRolTecnico()).as("check rolTecnico").isEqualTo(actual.getRolTecnico()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getFechaInicio()).as("check fechaInicio").isEqualTo(actual.getFechaInicio()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuerpoTecnicoUpdatableRelationshipsEquals(CuerpoTecnico expected, CuerpoTecnico actual) {
        assertThat(expected)
            .as("Verify CuerpoTecnico relationships")
            .satisfies(e -> assertThat(e.getAsociados()).as("check asociados").isEqualTo(actual.getAsociados()));
    }
}
