package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DirectivosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectivosAllPropertiesEquals(Directivos expected, Directivos actual) {
        assertDirectivosAutoGeneratedPropertiesEquals(expected, actual);
        assertDirectivosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectivosAllUpdatablePropertiesEquals(Directivos expected, Directivos actual) {
        assertDirectivosUpdatableFieldsEquals(expected, actual);
        assertDirectivosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectivosAutoGeneratedPropertiesEquals(Directivos expected, Directivos actual) {
        assertThat(expected)
            .as("Verify Directivos auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectivosUpdatableFieldsEquals(Directivos expected, Directivos actual) {
        assertThat(expected)
            .as("Verify Directivos relevant properties")
            .satisfies(e -> assertThat(e.getNombres()).as("check nombres").isEqualTo(actual.getNombres()))
            .satisfies(e -> assertThat(e.getApellidos()).as("check apellidos").isEqualTo(actual.getApellidos()))
            .satisfies(e -> assertThat(e.getCargo()).as("check cargo").isEqualTo(actual.getCargo()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getFechaEleccion()).as("check fechaEleccion").isEqualTo(actual.getFechaEleccion()))
            .satisfies(e -> assertThat(e.getFechaVencimiento()).as("check fechaVencimiento").isEqualTo(actual.getFechaVencimiento()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectivosUpdatableRelationshipsEquals(Directivos expected, Directivos actual) {}
}
