package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntrenamientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntrenamientoAllPropertiesEquals(Entrenamiento expected, Entrenamiento actual) {
        assertEntrenamientoAutoGeneratedPropertiesEquals(expected, actual);
        assertEntrenamientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntrenamientoAllUpdatablePropertiesEquals(Entrenamiento expected, Entrenamiento actual) {
        assertEntrenamientoUpdatableFieldsEquals(expected, actual);
        assertEntrenamientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntrenamientoAutoGeneratedPropertiesEquals(Entrenamiento expected, Entrenamiento actual) {
        assertThat(expected)
            .as("Verify Entrenamiento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntrenamientoUpdatableFieldsEquals(Entrenamiento expected, Entrenamiento actual) {
        assertThat(expected)
            .as("Verify Entrenamiento relevant properties")
            .satisfies(e -> assertThat(e.getFechaHora()).as("check fechaHora").isEqualTo(actual.getFechaHora()))
            .satisfies(e -> assertThat(e.getDuracion()).as("check duracion").isEqualTo(actual.getDuracion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntrenamientoUpdatableRelationshipsEquals(Entrenamiento expected, Entrenamiento actual) {
        assertThat(expected)
            .as("Verify Entrenamiento relationships")
            .satisfies(e -> assertThat(e.getCuerpoTecnico()).as("check cuerpoTecnico").isEqualTo(actual.getCuerpoTecnico()));
    }
}
