package cl.controlclub.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrevisionSaludAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrevisionSaludAllPropertiesEquals(PrevisionSalud expected, PrevisionSalud actual) {
        assertPrevisionSaludAutoGeneratedPropertiesEquals(expected, actual);
        assertPrevisionSaludAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrevisionSaludAllUpdatablePropertiesEquals(PrevisionSalud expected, PrevisionSalud actual) {
        assertPrevisionSaludUpdatableFieldsEquals(expected, actual);
        assertPrevisionSaludUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrevisionSaludAutoGeneratedPropertiesEquals(PrevisionSalud expected, PrevisionSalud actual) {
        assertThat(expected)
            .as("Verify PrevisionSalud auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrevisionSaludUpdatableFieldsEquals(PrevisionSalud expected, PrevisionSalud actual) {
        assertThat(expected)
            .as("Verify PrevisionSalud relevant properties")
            .satisfies(e -> assertThat(e.getTipoPrevision()).as("check tipoPrevision").isEqualTo(actual.getTipoPrevision()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrevisionSaludUpdatableRelationshipsEquals(PrevisionSalud expected, PrevisionSalud actual) {}
}
