package cl.controlclub.myapp.domain.enumeration;

/**
 * The RMComuna enumeration.
 */
public enum RMComuna {
    CERRILLOS,
    CERRO_NAVIA,
    CONCHALI,
    EL_BOSQUE,
    ESTACION_CENTRAL,
    HUECHURABA,
    INDEPENDENCIA,
    LA_CISTERNA,
    LA_FLORIDA,
    LA_GRANJA,
    LA_PINTANA,
    LA_REINA,
    LAS_CONDES,
    LO_BARNECHEA,
    LO_ESPEJO,
    LO_PRADO,
    MACUL,
    MAIPU,
    NUNOA,
    PADRE_HURTADO,
    PEDRO_AGUIRRE_CERDA,
    PENALOLEN,
    PIRQUE,
    PROVIDENCIA,
    PUDAHUEL,
    PUENTE_ALTO,
    QUILICURA,
    QUINTA_NORMAL,
    RECOLETA,
    RENCA,
    SAN_BERNARDO,
    SAN_JOAQUIN,
    SAN_JOSE_DE_MAIPO,
    SAN_MIGUEL,
    SAN_RAMON,
    SANTIAGO,
}
